name: gophermart

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.20
  
    steps:
      - name: Unit tests with coverage
        run: go test -timeout 30s -race -coverprofile=coverage.out -covermode=atomic ./...
