name: goph-keeper

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go get .

      - name: Unit testing
        run: CGO_ENABLED=1 go test -timeout 30s -race -coverprofile=coverage.out ./...
